### ISSUE TITLE
Help: How to use with typescript?

### ISSUE THREAD

**Issue by anabeatrizzz** [RukshanDias/vscode-jest-coverage#61]
Hello,

I would like to know if this extension is compatible with `.tsx` files because I tried to generate a report but there is no option for that. I already modified "Test File Format" field on settings to `.test.tsx`, but the option still doesn't appear

![Screen Shot 2024-08-29 at 3 04 32 PM](https://github.com/user-attachments/assets/0e95fa2c-f5a2-4c89-be35-1c9349c0088e)

**Comment by RukshanDias** [comment]
hi @anabeatrizzz, currently it only accepts .js & .ts type extensions. We will do some changes in accepted file formats & extensions near future, so will consider this as well. Thanks for pointing this, and sorry for taking time to answer.

**Comment by anabeatrizzz** [comment]
Okay. Thanks for your answer :)
@RukshanDias
